### ISSUE TITLE
org.hibernate.HibernateException: Access to DialectResolutionInfo cannot be null when 'hibernate.dialect' not set 

### ISSUE THREAD

**Issue by florianb** [testbefund/meta#12]
Aus dem API-Container-Log:

```
[api-5989bb8b4f-cbmjh] Caused by: org.hibernate.HibernateException: Access to DialectResolutionInfo cannot be null when 'hibernate.dialect' not set 
[api-5989bb8b4f-cbmjh]  at org.hibernate.engine.jdbc.dialect.internal.DialectFactoryImpl.determineDialect(DialectFactoryImpl.java:100) ~[hibernate-core-5.4.12.Final.jar!/:5.4.12.Final] 
[api-5989bb8b4f-cbmjh]  at org.hibernate.engine.jdbc.dialect.internal.DialectFactoryImpl.buildDialect(DialectFactoryImpl.java:54) ~[hibernate-core-5.4.12.Final.jar!/:5.4.12.Final] 
[api-5989bb8b4f-cbmjh]  at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator.initiateService(JdbcEnvironmentInitiator.java:137) ~[hibernate-core-5.4.12.Final.jar!/:5.4.12.Final] 
[api-5989bb8b4f-cbmjh]  at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator.initiateService(JdbcEnvironmentInitiator.java:35) ~[hibernate-core-5.4.12.Final.jar!/:5.4.12.Final] 
[api-5989bb8b4f-cbmjh]  at org.hibernate.boot.registry.internal.StandardServiceRegistryImpl.initiateService(StandardServiceRegistryImpl.java:101) ~[hibernate-core-5.4.12.Final.jar!/:5.4.12.Final] 
[api-5989bb8b4f-cbmjh]  at org.hibernate.service.internal.AbstractServiceRegistryImpl.createService(AbstractServiceRegistryImpl.java:263) ~[hibernate-core-5.4.12.Final.jar!/:5.4.12.Final] 
[api-5989bb8b4f-cbmjh]  ... 41 common frames omitted 
```

**Comment by Niklas345** [comment]
Hast du mal den ganzen Stacktrace samt vorherigen Exceptions? Das ist typischerweise ein Folgefehler, der passiert, wenn die Datenbank-Connection nicht zu stande kommt. Mögliche Ursachen:

- Datenbank nicht erreichbar
- Benutzername falsch
- Passwort falsch
- Ganz selten: Falscher jdbc driver geladen.

**Comment by florianb** [comment]
Kann am Verbindungsfehler gelegen haben, ich hab noch nicht nachgeguckt, ob der noch aktuell ist. Ich mach ihn vorerst zu und melde mich, falls er wieder auftaucht...
